// src/constants/mockData.js
// Mock data untuk aplikasi

export const MOCK_STUDENT = {
  id: '233510008',
  name: 'Ahmad Zaini',
  email: 'ahmadzaini942@student.uir.ac.id',
  phone: '+6282386763727',
  major: 'Teknik Informatika',
  semester: 6,
  gpa: 3.97,
  faculty: 'Teknik',
  university: 'Universitas Islam Riau (UIR)',
  campus_location: {
    name: 'UIR - Pekanbaru',
    latitude: 0.484,
    longitude: 101.438,
    address: 'Jl. Kaharudin Nasution No. 113, Pekanbaru 28284, Indonesia',
  },
  profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad',
};

export const MOCK_COURSES = [
  {
    id: 'IF-401',
    name: 'Pemrograman Web Lanjut',
    code: 'IF401',
    credits: 3,
    lecturer: 'Dr. Akmar Effendi S.Kom, M.Kom',
    lecturerEmail: 'akmar@uir.ac.id',
    lecturerPhone: '+6281234567890',
    schedule: 'Senin 13:00 - 14:40',
    room: '3C.2.08 Gedung C',
    description: 'Mempelajari konsep lanjutan dalam pengembangan aplikasi web modern, mencakup framework, database, dan deployment.',
    syllabus: [
      'HTML5 & CSS3 Advanced',
      'JavaScript ES6+',
      'React.js & Vue.js',
      'Backend dengan Node.js',
      'Database SQL & NoSQL',
      'REST API Design',
      'Deployment & DevOps',
    ],
    capacity: 30,
    registered: 25,
    isEnrolled: false,
    status: 'open',
  },
  {
    id: 'IF-402',
    name: 'Database Management Systems',
    code: 'IF402',
    credits: 4,
    lecturer: 'Prof. Bambang Sutrisno, S.T., M.Kom',
    lecturerEmail: 'bambang@uir.ac.id',
    lecturerPhone: '+6281234567891',
    schedule: 'Selasa , 14:50 - 16:30',
    room: 'Lab Komputer Basic Gedung C',
    description: 'Pembelajaran mendalam tentang sistem manajemen basis data relasional dan non-relasional.',
    syllabus: [
      'Database Design & Modeling',
      'SQL Queries',
      'Indexing & Optimization',
      'Transaction Management',
      'MongoDB & NoSQL',
      'Database Administration',
    ],
    capacity: 25,
    registered: 23,
    isEnrolled: true,
    status: 'open',
  },
  {
    id: 'IF-403',
    name: 'Mobile Application Development',
    code: 'IF403',
    credits: 3,
    lecturer: 'Dr. Siti Nurhaliza, S.Kom, M.Eng',
    lecturerEmail: 'siti@uir.ac.id',
    lecturerPhone: '+6281234567892',
    schedule: 'Rabu, 10:00 - 11:40',
    room: 'Lab Komputer 3 Gedung C',
    description: 'Pengembangan aplikasi mobile menggunakan React Native, Flutter, dan native Android/iOS.',
    syllabus: [
      'React Native Basics',
      'State Management',
      'Navigation Patterns',
      'API Integration',
      'Local Storage',
      'Testing & Debugging',
      'App Publishing',
    ],
    capacity: 40,
    registered: 38,
    isEnrolled: true,
    status: 'open',
  },
  {
    id: 'IF-404',
    name: 'Machine Learning Fundamentals',
    code: 'IF404',
    credits: 3,
    lecturer: 'Dr. Rudi Hartono, S.T., M.Phil',
    lecturerEmail: 'rudi@uir.ac.id',
    lecturerPhone: '+6281234567893',
    schedule: 'Senin - Rabu, 15:00 - 16:40',
    room: 'Ruang Lab Data Science',
    description: 'Pengenalan machine learning, supervised learning, dan unsupervised learning menggunakan Python.',
    syllabus: [
      'Linear Algebra & Statistics',
      'Python for ML',
      'Supervised Learning',
      'Unsupervised Learning',
      'Neural Networks',
      'Model Evaluation',
      'Real-world Applications',
    ],
    capacity: 20,
    registered: 18,
    isEnrolled: false,
    status: 'open',
  },
  {
    id: 'IF-405',
    name: 'Cloud Computing & DevOps',
    code: 'IF405',
    credits: 3,
    lecturer: 'Ir. Muhammad Rizki, M.Tech',
    lecturerEmail: 'rizki@uir.ac.id',
    lecturerPhone: '+6281234567894',
    schedule: 'Selasa - Kamis, 10:00 - 11:40',
    room: 'Ruang 401 Gedung D',
    description: 'Pembelajaran tentang cloud services, containerization, dan praktik DevOps modern.',
    syllabus: [
      'Cloud Concepts',
      'AWS / GCP / Azure',
      'Docker & Kubernetes',
      'CI/CD Pipelines',
      'Infrastructure as Code',
      'Monitoring & Logging',
    ],
    capacity: 35,
    registered: 30,
    isEnrolled: false,
    status: 'open',
  },
  {
    id: 'IF-406',
    name: 'Cybersecurity Essentials',
    code: 'IF406',
    credits: 2,
    lecturer: 'Ade Wijaya, S.Kom, M.Sc',
    lecturerEmail: 'ade@uir.ac.id',
    lecturerPhone: '+6281234567895',
    schedule: 'Kamis - Sabtu, 13:00 - 14:40',
    room: 'Ruang 201 Gedung A',
    description: 'Pengenalan dasar keamanan siber, enkripsi, dan praktik best practices.',
    syllabus: [
      'Security Fundamentals',
      'Encryption & Hashing',
      'Authentication & Authorization',
      'Network Security',
      'Web Application Security',
      'Incident Response',
    ],
    capacity: 30,
    registered: 26,
    isEnrolled: false,
    status: 'open',
  },
];

export const MOCK_QUICK_MENU = [
  {
    id: '1',
    title: 'Jadwal Kuliah',
    icon: 'calendar-clock',
    color: '#0066cc',
  },
  {
    id: '2',
    title: 'Nilai Saya',
    icon: 'school',
    color: '#00695c',
  },
  {
    id: '3',
    title: 'Tugas Saya',
    icon: 'clipboard-text-outline',
    color: '#f57c00',
  },
  {
    id: '4',
    title: 'Pengumuman',
    icon: 'bell-badge-outline',
    color: '#c62828',
  },
];

export const NOTIFICATION_SAMPLE = [
  {
    id: '1',
    title: 'Pengumuman Penting',
    message: 'Pendaftaran mata kuliah semester depan dibuka hari Senin',
    date: '2024-06-05',
    read: false,
  },
  {
    id: '2',
    title: 'Jadwal Ujian',
    message: 'Ujian Tengah Semester dimulai tanggal 20 Juni 2024',
    date: '2024-06-01',
    read: true,
  },
];